export const mockListings = [
  {
    id: "1",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 150000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Pedro Rojas 1",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2000",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/165.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "2",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 155000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Juan Pérez 2",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2001",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/22-01blog.png",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "3",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 160000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Diego Soto 3",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2002",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/3866855.jpeg",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "4",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 165000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Carlos Sanhueza 4",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2003",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/5.-MANITOU.png",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "5",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 170000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Miguel Tapia 5",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2004",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/aaabridora.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "6",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 175000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Andrés Silva 6",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2005",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/blog-03.webp",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "7",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 180000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Luis Martínez 7",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Bulldozer",
      marca: "Genérica",
      modelo: "M-2006",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/Bulldozer-Cat®-De-sus-Origenes-a-las-Innovaciones-que-Revolucionaron-la-Maquinaria-Pesada-600x403.jpg",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "8",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 185000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Fernando Gómez 8",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2007",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/BW_120-AD-5_1200.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "9",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 190000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Pedro Rojas 9",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2008",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/c9742b_ad585efef0764f74be60968f7b459592~mv2.avif",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "10",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 195000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Juan Pérez 10",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Camión Tolva",
      marca: "Genérica",
      modelo: "M-2009",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/Camion_Tolva-scaled.jpeg",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "11",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 200000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Diego Soto 11",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2010",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/cargador-frontal.jpg",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "12",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 205000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Carlos Sanhueza 12",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2011",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/cargadores-frontales-versus-retroexcavadoras.png",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "13",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 210000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Miguel Tapia 13",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2012",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/CM20160914-51687-18839.jpg",
      tonelajeCapacidad: "22 ton",
    },
  },
  {
    id: "14",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 215000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Andrés Silva 14",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2013",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/CM20220201-9fd19-0e5f1.jpg",
      tonelajeCapacidad: "23 ton",
    },
  },
  {
    id: "15",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 220000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Luis Martínez 15",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2014",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/como-funciona-una-retroexcavadora_img37612t1.jpg",
      tonelajeCapacidad: "24 ton",
    },
  },
  {
    id: "16",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 225000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Fernando Gómez 16",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2015",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/conarsac-blog-maquinaria-pesada.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "17",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 230000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Pedro Rojas 17",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2016",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/construction-site-building-1.jpg",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "18",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 235000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Juan Pérez 18",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2017",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/c_img_740x370.edlv2mjn3rh1t.jpg",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "19",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 240000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Diego Soto 19",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2018",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/dc5llcaxm06p9puowc4qefje5.jpg",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "20",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 245000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Carlos Sanhueza 20",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2019",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/digger-gf2d8e1c66_1280.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "21",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 250000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Miguel Tapia 21",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Camión Tolva",
      marca: "Genérica",
      modelo: "M-2020",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/dump-truck.jpg",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "22",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 255000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Andrés Silva 22",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2021",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/D_NQ_NP_745588-MLC74155088843_012024-O.webp",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "23",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 260000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Luis Martínez 23",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2022",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/e1ma6vqvbo7jxqmobafb89zis.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "24",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 265000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Fernando Gómez 24",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2023",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/el-arriendo-de-cargadores-frontales-la-solucion-para-el-trabajo-duro.png",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "25",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 270000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Pedro Rojas 25",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Motoniveladora",
      marca: "Genérica",
      modelo: "M-2024",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/equipamentos_motoniveladora_em_operaçao_inclinada.webp",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "26",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 275000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Juan Pérez 26",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Rodillo Compactador",
      marca: "Genérica",
      modelo: "M-2025",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/imagem-principal-rodillo.webp",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "27",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 280000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Diego Soto 27",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2026",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/IMG_20190221_125613.jpg",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "28",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 285000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Carlos Sanhueza 28",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Manipulador Telescópico",
      marca: "Genérica",
      modelo: "M-2027",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/Manipulador-telescopico-Genie.jpg",
      tonelajeCapacidad: "22 ton",
    },
  },
  {
    id: "29",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 290000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Miguel Tapia 29",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Manipulador Telescópico",
      marca: "Genérica",
      modelo: "M-2028",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/manipuladores-jcb-540-170-f3-950w.jpg",
      tonelajeCapacidad: "23 ton",
    },
  },
  {
    id: "30",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 295000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Andrés Silva 30",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2029",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/maquinaria-amarilla.jpg",
      tonelajeCapacidad: "24 ton",
    },
  },
  {
    id: "31",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 300000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Luis Martínez 31",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2030",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/maquinaria-pesada-1.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "32",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 305000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Fernando Gómez 32",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2031",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/Maquinaria-Pesada-Que-es-y-para-que-sirve-Komatsu-1.jpg",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "33",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 310000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Pedro Rojas 33",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2032",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/Maquinaria-pesada-scaled.webp",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "34",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 315000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Juan Pérez 34",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Motoniveladora",
      marca: "Genérica",
      modelo: "M-2033",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/Motoniveladora_01.jpg",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "35",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 320000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Diego Soto 35",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2034",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/Pala-cargadora-LW180K.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "36",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 325000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Carlos Sanhueza 36",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2035",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/Retroexcavadora.jpg",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "37",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 330000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Miguel Tapia 37",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2036",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/Tipos-de-maquinaria-pesada-en-Salfa.jpg",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "38",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 335000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Andrés Silva 38",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Grúa",
      marca: "Genérica",
      modelo: "M-2037",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/TowerCrane.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "39",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 340000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Luis Martínez 39",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Bulldozer",
      marca: "Genérica",
      modelo: "M-2038",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/tractor-bulldozer.jpg",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "40",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 345000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Fernando Gómez 40",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2039",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/TUWB7494.jpg",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "41",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 350000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Pedro Rojas 41",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2040",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/VO-SD110B_SD110B (3)_1640225522481-1300_CL-1300.jpg",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "42",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 355000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Juan Pérez 42",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2041",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/XE135U-371x247.webp",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "43",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 360000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Diego Soto 43",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2042",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/XE900D-3-371x247.webp",
      tonelajeCapacidad: "22 ton",
    },
  }
];

export type UserRole = "ADMIN" | "OPERADOR" | "CONTRATISTA";
export type UserStatus = "ACTIVO" | "SUSPENDIDO";

export interface MockUser {
  id: string;
  nombre: string;
  email: string;
  telefono: string;
  rol: UserRole;
  estado: UserStatus;
  fechaRegistro: string;
  claseLicencia?: string;
  poseeMaquinaria?: boolean;
  empresa?: string;
  passwordHash?: string;
}

// Availability data for operator calendars
export interface OperatorAvailability {
  operadorId: string;
  diasLibres: string[]; // ISO date strings (YYYY-MM-DD)
}

// Generate availability for demo operators
function generateAvailability(operadorId: string, seed: number): string[] {
  const dias: string[] = [];
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth();
  // Generate availability for current and next 2 months
  for (let m = 0; m < 3; m++) {
    const targetMonth = month + m;
    const targetYear = year + Math.floor(targetMonth / 12);
    const actualMonth = targetMonth % 12;
    const daysInMonth = new Date(targetYear, actualMonth + 1, 0).getDate();
    for (let d = 1; d <= daysInMonth; d++) {
      // Use a simple deterministic pattern based on seed
      if ((d + seed) % 3 !== 0 && (d + seed) % 7 !== 0) {
        const dateStr = `${targetYear}-${String(actualMonth + 1).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
        dias.push(dateStr);
      }
    }
  }
  return dias;
}

export const mockOperatorAvailability: OperatorAvailability[] = [
  { operadorId: "u2", diasLibres: generateAvailability("u2", 0) },
  { operadorId: "u3", diasLibres: generateAvailability("u3", 1) },
  { operadorId: "u5", diasLibres: generateAvailability("u5", 2) },
  { operadorId: "u8", diasLibres: generateAvailability("u8", 3) },
  { operadorId: "u9", diasLibres: generateAvailability("u9", 4) },
  { operadorId: "u11", diasLibres: generateAvailability("u11", 5) },
  { operadorId: "u12", diasLibres: generateAvailability("u12", 6) },
];

export const mockUsers: MockUser[] = [
  { id: "u1", nombre: "Admin Principal", email: "admin@maqconnect.cl", telefono: "+56 9 1111 1111", rol: "ADMIN", estado: "ACTIVO", fechaRegistro: "2024-01-15" },
  { id: "u2", nombre: "Pedro Rojas", email: "pedro.rojas@email.cl", telefono: "+56 9 2222 2222", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2024-03-10", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u3", nombre: "Juan Pérez", email: "juan.perez@email.cl", telefono: "+56 9 3333 3333", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2024-04-22", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u4", nombre: "Diego Soto", email: "diego.soto@email.cl", telefono: "+56 9 4444 4444", rol: "OPERADOR", estado: "SUSPENDIDO", fechaRegistro: "2024-05-05", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u5", nombre: "Carlos Sanhueza", email: "carlos.sanhueza@email.cl", telefono: "+56 9 5555 5555", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2024-06-18", claseLicencia: "Clase D", poseeMaquinaria: false },
  { id: "u6", nombre: "Constructora Andes SpA", email: "contacto@constructoraandes.cl", telefono: "+56 2 6666 6666", rol: "CONTRATISTA", estado: "ACTIVO", fechaRegistro: "2024-02-28", empresa: "Constructora Andes SpA" },
  { id: "u7", nombre: "Minera del Norte Ltda.", email: "operaciones@mineranorte.cl", telefono: "+56 2 7777 7777", rol: "CONTRATISTA", estado: "ACTIVO", fechaRegistro: "2024-07-01", empresa: "Minera del Norte Ltda." },
  { id: "u8", nombre: "Miguel Tapia", email: "miguel.tapia@email.cl", telefono: "+56 9 8888 8888", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2024-08-12", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u9", nombre: "Andrés Silva", email: "andres.silva@email.cl", telefono: "+56 9 9999 9999", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2024-09-03", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u10", nombre: "Inmobiliaria Pacífico SA", email: "info@inmopacifico.cl", telefono: "+56 2 1010 1010", rol: "CONTRATISTA", estado: "SUSPENDIDO", fechaRegistro: "2024-10-15", empresa: "Inmobiliaria Pacífico SA" },
  { id: "u11", nombre: "Luis Martínez", email: "luis.martinez@email.cl", telefono: "+56 9 1212 1212", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2025-01-08", claseLicencia: "Clase D", poseeMaquinaria: true },
  { id: "u12", nombre: "Fernando Gómez", email: "fernando.gomez@email.cl", telefono: "+56 9 1313 1313", rol: "OPERADOR", estado: "ACTIVO", fechaRegistro: "2025-02-20", claseLicencia: "Clase D", poseeMaquinaria: true },
];

export interface MockMessage {
  id: string;
  remitenteId: string;
  destinatarioId: string;
  asunto: string;
  contenido: string;
  fecha: string;
  leido: boolean;
}

export const mockMessages: MockMessage[] = [
  { id: "m1", remitenteId: "u1", destinatarioId: "u4", asunto: "Cuenta suspendida — Documentación pendiente", contenido: "Estimado Diego, su cuenta ha sido suspendida por falta de documentación vigente. Por favor envíe su licencia actualizada para reactivar su perfil.", fecha: "2026-03-15T10:30:00", leido: true },
  { id: "m2", remitenteId: "u1", destinatarioId: "u2", asunto: "Verificación de maquinaria", contenido: "Estimado Pedro, necesitamos verificar la información de su maquinaria M-2000. ¿Podría proporcionar fotos actualizadas?", fecha: "2026-03-18T14:00:00", leido: false },
  { id: "m3", remitenteId: "u1", destinatarioId: "u6", asunto: "Bienvenida a MaqConnect", contenido: "Bienvenidos a MaqConnect, Constructora Andes. Cualquier duda sobre cómo publicar solicitudes de arriendo, no dude en contactarnos.", fecha: "2026-03-10T09:00:00", leido: true },
  { id: "m4", remitenteId: "u1", destinatarioId: "u10", asunto: "Cuenta suspendida — Pago pendiente", contenido: "Estimada Inmobiliaria Pacífico, su cuenta ha sido suspendida por un pago pendiente. Regularice su situación para continuar usando la plataforma.", fecha: "2026-03-20T11:15:00", leido: false },
  { id: "m5", remitenteId: "u1", destinatarioId: "u3", asunto: "Actualización de perfil requerida", contenido: "Estimado Juan, su perfil necesita actualización de datos de contacto. Por favor revise su información.", fecha: "2026-03-19T16:45:00", leido: true },
];
