export const mockListings = [
  {
    id: "1",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 150000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Pedro Rojas 1",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2000",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/165.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "2",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 155000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Juan Pérez 2",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2001",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/22-01blog.png",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "3",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 160000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Diego Soto 3",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2002",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/3866855.jpeg",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "4",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 165000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Carlos Sanhueza 4",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2003",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/5.-MANITOU.png",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "5",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 170000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Miguel Tapia 5",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2004",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/aaabridora.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "6",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 175000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Andrés Silva 6",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2005",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/blog-03.webp",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "7",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 180000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Luis Martínez 7",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Bulldozer",
      marca: "Genérica",
      modelo: "M-2006",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/Bulldozer-Cat®-De-sus-Origenes-a-las-Innovaciones-que-Revolucionaron-la-Maquinaria-Pesada-600x403.jpg",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "8",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 185000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Fernando Gómez 8",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2007",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/BW_120-AD-5_1200.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "9",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 190000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Pedro Rojas 9",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2008",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/c9742b_ad585efef0764f74be60968f7b459592~mv2.avif",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "10",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 195000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Juan Pérez 10",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Camión Tolva",
      marca: "Genérica",
      modelo: "M-2009",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/Camion_Tolva-scaled.jpeg",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "11",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 200000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Diego Soto 11",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2010",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/cargador-frontal.jpg",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "12",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 205000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Carlos Sanhueza 12",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2011",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/cargadores-frontales-versus-retroexcavadoras.png",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "13",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 210000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Miguel Tapia 13",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2012",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/CM20160914-51687-18839.jpg",
      tonelajeCapacidad: "22 ton",
    },
  },
  {
    id: "14",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 215000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Andrés Silva 14",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2013",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/CM20220201-9fd19-0e5f1.jpg",
      tonelajeCapacidad: "23 ton",
    },
  },
  {
    id: "15",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 220000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Luis Martínez 15",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2014",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/como-funciona-una-retroexcavadora_img37612t1.jpg",
      tonelajeCapacidad: "24 ton",
    },
  },
  {
    id: "16",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 225000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Fernando Gómez 16",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2015",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/conarsac-blog-maquinaria-pesada.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "17",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 230000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Pedro Rojas 17",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2016",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/construction-site-building-1.jpg",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "18",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 235000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Juan Pérez 18",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2017",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/c_img_740x370.edlv2mjn3rh1t.jpg",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "19",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 240000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Diego Soto 19",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2018",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/dc5llcaxm06p9puowc4qefje5.jpg",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "20",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 245000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Carlos Sanhueza 20",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2019",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/digger-gf2d8e1c66_1280.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "21",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 250000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Miguel Tapia 21",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Camión Tolva",
      marca: "Genérica",
      modelo: "M-2020",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/dump-truck.jpg",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "22",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 255000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Andrés Silva 22",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2021",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/D_NQ_NP_745588-MLC74155088843_012024-O.webp",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "23",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 260000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Luis Martínez 23",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2022",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/e1ma6vqvbo7jxqmobafb89zis.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "24",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 265000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Fernando Gómez 24",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2023",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/el-arriendo-de-cargadores-frontales-la-solucion-para-el-trabajo-duro.png",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "25",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 270000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Pedro Rojas 25",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Motoniveladora",
      marca: "Genérica",
      modelo: "M-2024",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/equipamentos_motoniveladora_em_operaçao_inclinada.webp",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "26",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 275000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Juan Pérez 26",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Rodillo Compactador",
      marca: "Genérica",
      modelo: "M-2025",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/imagem-principal-rodillo.webp",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "27",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 280000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Diego Soto 27",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2026",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/IMG_20190221_125613.jpg",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "28",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 285000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Carlos Sanhueza 28",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Manipulador Telescópico",
      marca: "Genérica",
      modelo: "M-2027",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/Manipulador-telescopico-Genie.jpg",
      tonelajeCapacidad: "22 ton",
    },
  },
  {
    id: "29",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 290000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Miguel Tapia 29",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Manipulador Telescópico",
      marca: "Genérica",
      modelo: "M-2028",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/manipuladores-jcb-540-170-f3-950w.jpg",
      tonelajeCapacidad: "23 ton",
    },
  },
  {
    id: "30",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 295000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Andrés Silva 30",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2029",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/maquinaria-amarilla.jpg",
      tonelajeCapacidad: "24 ton",
    },
  },
  {
    id: "31",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 300000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Luis Martínez 31",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2030",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/maquinaria-pesada-1.jpg",
      tonelajeCapacidad: "10 ton",
    },
  },
  {
    id: "32",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 305000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Fernando Gómez 32",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2031",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/Maquinaria-Pesada-Que-es-y-para-que-sirve-Komatsu-1.jpg",
      tonelajeCapacidad: "11 ton",
    },
  },
  {
    id: "33",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 310000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Pedro Rojas 33",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2032",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/Maquinaria-pesada-scaled.webp",
      tonelajeCapacidad: "12 ton",
    },
  },
  {
    id: "34",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 315000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Juan Pérez 34",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Motoniveladora",
      marca: "Genérica",
      modelo: "M-2033",
      year: 2018,
      condicion: "BUENA",
      fotoUrl: "/Motoniveladora_01.jpg",
      tonelajeCapacidad: "13 ton",
    },
  },
  {
    id: "35",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 320000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Diego Soto 35",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Cargador Frontal",
      marca: "Genérica",
      modelo: "M-2034",
      year: 2019,
      condicion: "BUENA",
      fotoUrl: "/Pala-cargadora-LW180K.jpg",
      tonelajeCapacidad: "14 ton",
    },
  },
  {
    id: "36",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 325000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Carlos Sanhueza 36",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Retroexcavadora",
      marca: "Genérica",
      modelo: "M-2035",
      year: 2020,
      condicion: "BUENA",
      fotoUrl: "/Retroexcavadora.jpg",
      tonelajeCapacidad: "15 ton",
    },
  },
  {
    id: "37",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 330000,
    regionDisponible: "Región del Biobío",
    ciudadDisponible: "Concepción",
    usuario: {
      nombre: "Operador Miguel Tapia 37",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2036",
      year: 2021,
      condicion: "BUENA",
      fotoUrl: "/Tipos-de-maquinaria-pesada-en-Salfa.jpg",
      tonelajeCapacidad: "16 ton",
    },
  },
  {
    id: "38",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 335000,
    regionDisponible: "Región de Valparaíso",
    ciudadDisponible: "Viña del Mar",
    usuario: {
      nombre: "Operador Andrés Silva 38",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Grúa",
      marca: "Genérica",
      modelo: "M-2037",
      year: 2022,
      condicion: "BUENA",
      fotoUrl: "/TowerCrane.jpg",
      tonelajeCapacidad: "17 ton",
    },
  },
  {
    id: "39",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 340000,
    regionDisponible: "Región de Antofagasta",
    ciudadDisponible: "Antofagasta",
    usuario: {
      nombre: "Operador Luis Martínez 39",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Bulldozer",
      marca: "Genérica",
      modelo: "M-2038",
      year: 2023,
      condicion: "BUENA",
      fotoUrl: "/tractor-bulldozer.jpg",
      tonelajeCapacidad: "18 ton",
    },
  },
  {
    id: "40",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 345000,
    regionDisponible: "Región de Coquimbo",
    ciudadDisponible: "La Serena",
    usuario: {
      nombre: "Operador Fernando Gómez 40",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2039",
      year: 2024,
      condicion: "BUENA",
      fotoUrl: "/TUWB7494.jpg",
      tonelajeCapacidad: "19 ton",
    },
  },
  {
    id: "41",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 350000,
    regionDisponible: "Región de Tarapacá",
    ciudadDisponible: "Iquique",
    usuario: {
      nombre: "Operador Pedro Rojas 41",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Maquinaria Pesada",
      marca: "Genérica",
      modelo: "M-2040",
      year: 2015,
      condicion: "BUENA",
      fotoUrl: "/VO-SD110B_SD110B (3)_1640225522481-1300_CL-1300.jpg",
      tonelajeCapacidad: "20 ton",
    },
  },
  {
    id: "42",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 355000,
    regionDisponible: "Región del Maule",
    ciudadDisponible: "Talca",
    usuario: {
      nombre: "Operador Juan Pérez 42",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2041",
      year: 2016,
      condicion: "BUENA",
      fotoUrl: "/XE135U-371x247.webp",
      tonelajeCapacidad: "21 ton",
    },
  },
  {
    id: "43",
    tipoServicio: "ARRIENDO_CON_OPERADOR",
    precioReferencial: 360000,
    regionDisponible: "Región Metropolitana",
    ciudadDisponible: "Santiago",
    usuario: {
      nombre: "Operador Diego Soto 43",
      rol: "PROVEEDOR",
      claseLicencia: "Clase D",
      poseeMaquinaria: true,
    },
    maquinaria: {
      tipoMaquinaria: "Excavadora",
      marca: "Genérica",
      modelo: "M-2042",
      year: 2017,
      condicion: "BUENA",
      fotoUrl: "/XE900D-3-371x247.webp",
      tonelajeCapacidad: "22 ton",
    },
  }
];